# Generated by Django 6.0.7 on 2026-07-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=150)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('number_of_properties', models.PositiveIntegerField()),
                ('id_document', models.FileField(upload_to='landlord_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
