# Generated by Django 6.0.7 on 2026-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='house_type',
            field=models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('Silver House (Mabati)', 'Silver House (Mabati)'), ('Hostel', 'Hostel'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom'), ('Shared Room', 'Shared Room'), ('Self Contained', 'Self Contained')], max_length=50),
        ),
    ]
