# Generated by Django 6.0.7 on 2026-07-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_university',
            field=models.PositiveIntegerField(default=5, help_text='Distance to the university (minutes)'),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='water',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
