"""
Django settings for housecampus project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path

# -----------------------------------------------------------------------------
# BASE DIRECTORY
# -----------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# SECURITY
# -----------------------------------------------------------------------------

SECRET_KEY = "django-insecure-kyyq$gh_*dpy%y0(p#*xwrqeaj+m+!+q%&c5(r!_&qhos)o6j8"

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "housecampuske.com",
    "www.housecampuske.com",
    "housecampuske.onrender.com",
    "wdd130-ge6x.onrender.com",
]

# -----------------------------------------------------------------------------
# APPLICATIONS
# -----------------------------------------------------------------------------

INSTALLED_APPS = [
    "jazzmin",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "cloudinary",
    "cloudinary_storage",

    "accounts",
    "properties",
    "portal",
    "home",
    "landlord",
    "messaging",
]

# -----------------------------------------------------------------------------
# JAZZMIN SETTINGS
# -----------------------------------------------------------------------------

JAZZMIN_SETTINGS = {

    "site_title": "HOUSE CAMPUS Admin",

    "site_header": "HOUSE CAMPUS",

    "site_brand": "HOUSE CAMPUS",

    "welcome_sign": "Welcome to HOUSE CAMPUS Administration",

    "copyright": "© 2026 HOUSE CAMPUS",

    "site_logo": "images/logo.png",

    "login_logo": "images/logo.png",

    "site_icon": "images/favicon.png",

    "navigation_expanded": True,

    "show_sidebar": True,

    "theme": "flatly",

    "show_ui_builder": False,

    "topmenu_links": [

        {
            "name": "Website",
            "url": "/",
            "new_window": True,
        },

        {
            "model": "accounts.User",
        },

        {
            "app": "properties",
        },

    ],

    "icons": {

        "auth.user": "fas fa-users",

        "accounts.user": "fas fa-user-circle",

        "properties.property": "fas fa-home",

        "landlord.landlordapplication": "fas fa-building",

        "messaging.message": "fas fa-envelope",

    },

}

# -----------------------------------------------------------------------------
# MIDDLEWARE
# -----------------------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------------------------------------------------------
# URLS
# -----------------------------------------------------------------------------

ROOT_URLCONF = "housecampus.urls"

# -----------------------------------------------------------------------------
# TEMPLATES
# -----------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# -----------------------------------------------------------------------------
# WSGI
# -----------------------------------------------------------------------------

WSGI_APPLICATION = "housecampus.wsgi.application"

# -----------------------------------------------------------------------------
# DATABASE
# -----------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -----------------------------------------------------------------------------
# PASSWORD VALIDATION
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# -----------------------------------------------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# -----------------------------------------------------------------------------
# STATIC FILES
# -----------------------------------------------------------------------------

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# -----------------------------------------------------------------------------
# MEDIA FILES
# -----------------------------------------------------------------------------

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# -----------------------------------------------------------------------------
# CUSTOM USER MODEL
# -----------------------------------------------------------------------------

AUTH_USER_MODEL = "accounts.User"

# -----------------------------------------------------------------------------
# LOGIN SETTINGS
# -----------------------------------------------------------------------------

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "dashboard"

LOGOUT_REDIRECT_URL = "home"

# -----------------------------------------------------------------------------
# DEFAULT PRIMARY KEY
# -----------------------------------------------------------------------------

import os
import cloudinary

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True,
)

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}