# Generated by Django 6.0.7 on 2026-07-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Example: 254712345678', max_length=20, null=True),
        ),
    ]
